import argparse
import ast


def get_finetune_params():
    def parse_list(input_string):
        return ast.literal_eval(input_string)

    parser = argparse.ArgumentParser(description='Finetune on downstream tasks')

    # task settings
    parser.add_argument('--task_cfg_path',  type=str, default='finetune/task_configs/mutation_5_gene.yaml', help='Path to the task configuration file')
    parser.add_argument('--exp_name',       type=str, default='', help='Experiment name')
    parser.add_argument('--hf_token',       type=str, default='', help='Hugging face token, needed to load the prov-gigapath model')
    parser.add_argument('--pat_strat',      action='store_true', default=False, help='Patient stratification')
    parser.add_argument('--run_inference',  action='store_true', default=False, help='Only run inference')
    parser.add_argument('--sliding_window_inference',action='store_true', default=False, help='run inference with a sliding window')
    parser.add_argument('--create_y',       action='store_true', default=False, help='Create IHC tile score (from IHC0)')
    parser.add_argument('--create_y_map',   action='store_true', default=False, help='Create IHC tile score map using sliding window inference (with IHC0)')
    parser.add_argument('--create_cancer_map', action='store_true', default=False, help='Create HE tile cancer score map using sliding window inference (with slide cancer model)')
    parser.add_argument('--create_HER2_status_map', action='store_true', default=False, help='Create HE tile HER2 status score map using sliding window inference (with THUFA slide HER2 status model)')
    parser.add_argument('--create_pred_y',  action='store_true', default=False, help='Create HE tile score (from Baseline0)')
    parser.add_argument('--predict_cancer', action='store_true', default=False, help='Predict malignant vs benign per tile')

    # input data settings
    parser.add_argument('--dataset_csv',    type=str, default='/home/shacharcohen/workspace/WSI/metadata_csvs/largest_with_taylor.csv', help='Dataset csv file')
    parser.add_argument('--split_dir',      type=str, default='', help='Split directory')
    parser.add_argument('--root_path',      type=str, default='', help='The tile encodings path')
    parser.add_argument('--tile_y_pred_file_name',type=str, default='', help='The tile y predictions file name')
    parser.add_argument('--ext_tile_y_pred_file_name',type=str, default='', help='The external model tile y predictions file name')
    parser.add_argument('--tile_size',      type=int, default=256, help='Tile size in pixels')
    parser.add_argument('--max_wsi_size',   type=int, default=262144, help='Maximum WSI size in pixels for the longer side (width or height).')
    parser.add_argument('--label',          type=str, default='onco_score_26', help='Column name of the label')
    parser.add_argument('--teacher_label',  type=str, default=None, help='Column name of the teacher label')
    parser.add_argument('--censoreship',    type=str, default=None, help='Column name of the censoreship column')
    parser.add_argument('--train_dataset',  type=parse_list, default=['TAILORx_1'], help='Name of datasets to train on')
    parser.add_argument('--val_dataset',    type=parse_list, default=[], help='Name of datasets to validate on')
    parser.add_argument('--test_dataset',   type=parse_list, default=[], help='Name of datasets to test on')
    parser.add_argument('--train_fold',     type=parse_list, default=[2,3,4,5], help='Folds to train on')
    parser.add_argument('--val_fold',       type=parse_list, default=[1], help='Folds to train on')
    parser.add_argument('--test_fold',      type=parse_list, default=[6], help='Folds to test on')
    parser.add_argument('--test_on_all',    action='store_true', default=False, help='Test also on slides without label')
    parser.add_argument('--generate_heatmap',action='store_true', default=False, help='Generate a heatmap for a single slide')
    parser.add_argument('--get_single_slide',type=str, default=None, help='Initialize dataset with a single slide')
    parser.add_argument('--window_size',    type=int, default=10, help='Sliding window size when generating a heatmap')
    parser.add_argument('--stride',         type=int, default=1, help='Sliding window stride when generating a heatmap')
    parser.add_argument('--y_and_tumor_from_map', action='store_true', default=False, help='Get tile scores (y) and tumor mask from the generated maps instead of loading from files')
    parser.add_argument('--load_tile_logits', action='store_true', default=False, help='Load tile logits instead of predicting them')
    parser.add_argument('--target_mpp',     type=float, help='Target tiles MPP', default=0.5, choices=[0.5, 1, 2])
    parser.add_argument('--all_he_tiles',   action='store_true', default=False, help='Use all HE tiles for prediction')

    # model settings
    parser.add_argument('--model_arch',     type=str, default='longnet_enc12l768d')
    parser.add_argument('--input_dim',      type=int, default=1536, help='Dimension of input tile embeddings for slide classifier')
    parser.add_argument('--tile_input_dim', type=int, default=1536, help='Dimension of input tile embeddings for tile classifier')
    parser.add_argument('--latent_dim',     type=int, default=768, help='Hidden dimension of the slide encoder')
    parser.add_argument('--feat_layer',     type=str, default='11', help='The layers from which embeddings are fed to the classifier, e.g., 5-11 for taking out the 5th and 11th layers')
    parser.add_argument('--pretrained',     type=str, default='', help='Pretrained GigaPath slide encoder')
    parser.add_argument('--freeze',         action='store_true', default=False, help='Freeze pretrained model')
    parser.add_argument('--clinical_features',action='store_true', default=False, help='Use clinical features in addition to the SSL model features')
    parser.add_argument('--use_tile_classification',action='store_true', default=False, help='Use local tile scores for training')
    parser.add_argument('--window_training',action='store_true', default=False, help='Use local window scores for training')
    parser.add_argument('--student_training',action='store_true', default=False, help='Use IHC model as a teacher for training')
    parser.add_argument('--matching_tiles_training',action='store_true', default=False, help='Use IHC tile features as a teacher for training')
    parser.add_argument('--paired_training_mw',action='store_true', default=False, help='Use paired H&E and IHC matched tiles for training')
    parser.add_argument('--paired_mw_w_cancer',action='store_true', default=False, help='Use paired H&E and IHC matched tiles with cancer probabilities for training')
    parser.add_argument('--paired_mw_cancer_scale',action='store_true', default=False, help='Use paired H&E and IHC matched tiles with cancer probabilities as features scale for training')
    parser.add_argument('--malig_paired_mw',action='store_true', default=False, help='Use paired H&E and IHC matched malignant tiles for training')
    parser.add_argument('--malig_baseline' ,action='store_true', default=False, help='Use IHC matched malignant tiles for baseline training')
    parser.add_argument('--replace_benign_w_zero',action='store_true', default=False, help='Replace benign tiles with zero features for training')
    parser.add_argument('--paired_training_mb',action='store_true', default=False, help='Concat paired H&E and IHC image features for training')
    parser.add_argument('--paired_training_cat_h',action='store_true', default=False, help='Concat paired H&E and IHC slide features for training')
    parser.add_argument('--tile_slide_training',action='store_true', default=False, help='Train with both tile and slide level supervision, where tile level supervision is from IHC tile scores')
    parser.add_argument('--tile_slide_model',action='store_true', default=False, help='Train with both tile and slide level supervision in a single model')
    parser.add_argument('--use_tile_classifier',action='store_true', default=False, help='Use tile classifier for tile level predictions')
    parser.add_argument('--compress_features',action='store_true', default=False, help='Compress IHC tile features to lower dimension')
    parser.add_argument('--cycle_gan_train',action='store_true', default=False, help='Train CycleGAN to generate IHC tiles from H&E tiles')
    parser.add_argument('--synth_ihc_train',action='store_true', default=False, help='Use synthetic IHC tiles for training')
    parser.add_argument('--save_x',         action='store_true', default=False, help='Save compressed IHC tile features')
    parser.add_argument('--save_reg_x',     action='store_true', default=False, help='Save regressed IHC compressed tile features from H&E embeddings')
    parser.add_argument('--cat_random',     action='store_true', default=False, help='Concatenate random features to tile features')
    parser.add_argument('--cat_ihc',        action='store_true', default=False, help='Concatenate IHC tile features to H&E tile features')
    parser.add_argument('--cat_y',          action='store_true', default=False, help='Concatenate IHC tile score (from IHC0) to H&E tile features')
    parser.add_argument('--cat_x',          action='store_true', default=False, help='Concatenate IHC compressed features (from IHC2) to H&E tile features')
    parser.add_argument('--trim_images',    action='store_true', default=False, help='Concatenate IHC compressed features (from IHC2) to trimmed H&E tile features')
    parser.add_argument('--x_as_sb',        action='store_true', default=False, help='Use IHC compressed features (from IHC2) as modulation (scale and bias) for H&E tile features')
    parser.add_argument('--score_can_as_sb',action='store_true', default=False, help='Use tile scores and cancer probs as modulation (scale and bias) for H&E tile features')
    parser.add_argument('--score_can_as_bs',action='store_true', default=False, help='Use tile scores and cancer probs as modulation (bias and scale) for H&E tile features')
    parser.add_argument('--film',           action='store_true', default=False, help='Use tile scores and cancer probs as modulation (bias and scale) for H&E tile features via FiLM layer')
    parser.add_argument('--weighted_film',  action='store_true', default=False, help='Use weighted tile scores and cancer probs as modulation (features and weights) for H&E tile features via FiLM layer')
    parser.add_argument('--const_tl',       action='store_true', default=False, help='Use const tile scores (3) as modulation (bias and scale) for H&E tile features via FiLM layer')
    parser.add_argument('--const_cp',       action='store_true', default=False, help='Use const cancer probs (1) as modulation (bias and scale) for H&E tile features via FiLM layer')
    parser.add_argument('--cat_reg_x',      action='store_true', default=False, help='Concatenate regressed IHC compressed features from H&E tile features')
    parser.add_argument('--train_on_y',     action='store_true', default=False, help='Train on tiles scores (y - from IHC0)')
    parser.add_argument('--add_virchow2_features',action='store_true', default=False, help='Train on tiles scores (y - from IHC0) with adding Virchow2 features')
    parser.add_argument('--add_uni2_features',action='store_true', default=False, help='Train on tiles scores (y - from IHC0) with adding UNI2 features')
    parser.add_argument('--add_conch_features',action='store_true', default=False, help='Train on tiles scores (y - from IHC0) with adding CONCH features')
    parser.add_argument('--external_model_logits',action='store_true', default=False, help='Modulate tile features using external model HER2 scores logits')
    parser.add_argument('--cnn_on_y',       action='store_true', default=False, help='Train on tiles scores (y - from IHC0) with CNN on tiles instead of linear layer on GigaPath features')
    parser.add_argument('--pred_y_baseline',action='store_true', default=False, help='Predict tiles scores (y - from IHC0) with Baseline0')
    parser.add_argument('--pred_y',         action='store_true', default=False, help='Predict tiles scores (y - from IHC0) with local model')
    parser.add_argument('--pred_from_tumor',action='store_true', default=False, help='Predict slide score with only tumor tiles')
    parser.add_argument('--only_tumor_tiles',action='store_true', default=False, help='Train only on tumor HE tile scores (y - from IHC0)')
    parser.add_argument('--only_annotated_tiles',action='store_true', default=False, help='Predict only on tumor/non-tumor annotated tiles')
    parser.add_argument('--only_annotated', action='store_true', default=False, help='Use only annotated pairs of slides')
    parser.add_argument('--conf_score',     action='store_true', default=False, help='Predict tile scores along with confidence scores')
    parser.add_argument('--global_pool',    action='store_true', default=False, help='Use global pooling, will use [CLS] token if False')
    parser.add_argument('--model_ckpt',     type=str, default='', help='Model checkpoint path')
    parser.add_argument('--teacher_model_ckpt',type=str, default='', help='Teacher model checkpoint path')
    parser.add_argument('--tile_model_ckpt',type=str, default='', help='Tile model checkpoint path')

    # training settings
    parser.add_argument('--seed',           type=int, default=0, help='Random seed')
    parser.add_argument('--epochs',         type=int, default=5, help='Number of training epochs')
    parser.add_argument('--warmup_epochs',  type=int, default=1, help='Number of warmup epochs')
    parser.add_argument('--batch_size',     type=int, default=1, help='Current version only supports batch size of 1')
    parser.add_argument('--lr',             type=float, default=None, help='Learning rate')
    parser.add_argument('--blr',            type=float, default=4e-3, help='Base learning rate, will caculate the learning rate based on batch size')
    parser.add_argument('--min_lr',         type=float, default=1e-6, help='Minimum learning rate')
    parser.add_argument('--lr_scheduler',   type=str, default='cosine', help='Learning rate scheduler', choices=['cosine', 'fixed'])
    parser.add_argument('--gc',             type=int, default=32, help='Gradient accumulation')
    parser.add_argument('--folds',          type=int, default=10, help='Number of folds for cross-validation')
    parser.add_argument('--optim',          type=str, default='adamw', help='Optimizer', choices=['adam', 'adamw'])
    parser.add_argument('--optim_wd',       type=float, default=1e-5, help='Weight decay')
    parser.add_argument('--layer_decay',    type=float, default=0.95, help='Layer-wise learning rate decay')
    parser.add_argument('--dropout',        type=float, default=0.1, help='Dropout rate')
    parser.add_argument('--drop_path_rate', type=float, default=0.1, help='Drop path rate')
    parser.add_argument('--val_r',          type=float, default=0.1, help='Ratio of data used for validation')
    parser.add_argument('--model_select',   type=str, default='last_epoch', help='Criteria for choosing the model checkpoint', choices=['val', 'last_epoch'])
    parser.add_argument('--save_dir',       type=str, default='', help='Save directory')
    parser.add_argument('--num_workers',    type=int, default=20, help='Number of workers')
    parser.add_argument('--report_to',      type=str, default='tensorboard', help='Logger used for recording', choices=['wandb', 'tensorboard'])
    parser.add_argument('--loss_fn',        type=str, default='mse', help='Which loss to use in continuous setting', choices=['mse', 'mae', 'huber', 'logcosh', 'cox', 'trunc_mse', 'weighted_mse', 'coral', 'a_mse'])
    parser.add_argument('--fp16',           action='store_true', default=True, help='Fp16 training')
    parser.add_argument('--weighted_sample',action='store_true', default=False, help='Weighted sampling')
    parser.add_argument('--survival'       ,action='store_true', default=False, help='Predict survival, it will load censoreship data')
    parser.add_argument('--oversample',     action='store_true', default=False, help='oversample non frequent classes')
    parser.add_argument('--reduction',      type=int, default=1, help='Feature reduction factor, e.g., 2 for 1536 -> 768')
    parser.add_argument('--comp_power',     type=int, default=1, help='Feature compression power, e.g., 2 ** 4 for 1536 -> 96')
    parser.add_argument('--x_dim',          type=int, default=0, help='Compressed IHC features dimension')
    parser.add_argument('--cl_HE_feat',     action='store_true', default=False, help='Contrastive learning on compressed HE features')
    parser.add_argument('--pred_mean_std',  action='store_true', default=False, help='Apply AdaIN on HE features')
    parser.add_argument('--save_plots',     action='store_true', default=False, help='Save labels and predictions plots')
    parser.add_argument('--keep_logits_labels',    action='store_true', default=False, help='Keep logits and labels for processing during runtime')
    

    return parser.parse_args()
